language: ruby
cache:
  directories:
    - vendor/bundle
    - sdk

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1

script:
  - |
    version='4333796'

    if [ "$(cat sdk/.sdk_tools_version || echo)" != "$version" ]; then
      rm -fr sdk || :
      mkdir -p sdk/licenses
      curl -o sdk-tools-linux.zip "https://dl.google.com/android/repository/sdk-tools-linux-$version.zip"
      unzip "sdk-tools-linux.zip" -d sdk
    fi

    echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > sdk/licenses/android-sdk-license
    sdk/tools/bin/sdkmanager "build-tools;27.0.3"
  - ANDROID_HOME="$PWD/sdk" bundle exec rake spec
