name: 'Run lint on every commits'

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby
      - run: bundle exec rake rubocop