name: 'Run tests on every commits'

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  spec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ruby-version:
          - '2.7'
          - '3.0'
          - '3.1'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundle-cache: true
      - run: bundle exec rake rspecs spec_docs
        env:
          APKANALYZER_PATH: ${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin/apkanalyzer